apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "resource.default.name" $ }}
  infrastructureRef:
    apiVersion: {{ include "infrastructureApiVersion" . }}
    kind: OpenStackCluster
    name: {{ include "resource.default.name" $ }}
  {{- if or .Values.clusterNetwork.serviceCidrs .Values.clusterNetwork.podCidrs }}
  clusterNetwork:
    {{- if or .Values.clusterNetwork.serviceCidrs }}
    services:
      cidrBlocks:
      {{- range .Values.clusterNetwork.serviceCidrs }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- if or .Values.clusterNetwork.podCidrs }}
    pods:
      cidrBlocks:
      {{- range .Values.clusterNetwork.podCidrs }}
      - {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
