{{- range $name, $value := .Values.nodePools }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    # Let Cluster API clean this resource up.
    helm.sh/resource-policy: keep
  name: {{ include "resource.default.name" $ }}-{{ $name }}-{{- include "kubeadmConfigTemplateRevision" (merge (dict "pool" $value) $) }}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      {{- include "kubeadmConfigTemplateSpec" (merge (dict "pool" (set $value "name" $name)) $) | nindent 6 -}}
{{- end }}
