apiVersion: v2
name: cluster-openstack
description: A helm chart for creating Cluster API clusters with the OpenStack infrastructure provider (CAPO).
home: https://github.com/thg-ice/cluster-openstack
type: application
version: 0.18.0
restrictions:
  compatibleProviders:
    - openstack
icon: https://s.giantswarm.io/app-icons/openstack/1/light.svg
dependencies:
  - name: cluster-shared
    version: "0.6.3"
    repository: "https://giantswarm.github.io/cluster-catalog"
